### Se necesita la extension de REST Client para usar las rutas de abajo en vs code
###@host = http://25.98.13.19:5555
@host = https://localhost:5001
GET {{host}}/api/Category/Test HTTP/1.1
###
GET {{host}}/api/Category/GetAll HTTP/1.1
###
GET {{host}}/api/Category/GetId?id=16 HTTP/1.1
###
GET {{host}}/api/Category/GetByCatalog?id=1 HTTP/1.1
###
POST {{host}}/api/Category/Post HTTP/1.1
Content-Type: application/json

{
    "id":16,
    "name":"Mamey",
    "catalog":{
        "id":2,
        "name":"Destilados"
    }
}
### 
PUT {{host}}/api/Category/Put HTTP/1.1
Content-Type: application/json

{
    "id": 16,
    "name": "Alvastos",
    "catalog": {
      "id": 2,
      "name": "Destilados"
    }
  }
###
DELETE {{host}}/api/Category/Delete?id=16 HTTP/1.1