@host = https://localhost:5001/api/Product
GET {{host}}/Test HTTP/1.1
###
GET {{host}}/GetAll HTTP/1.1
###
GET {{host}}/GetId?id=149 HTTP/1.1
###
GET {{host}}/GetList?ids=10&ids=12 HTTP/1.1
###
GET {{host}}/GetClasification?clasification=Vodka HTTP/1.1
###
GET {{host}}/GetCatalog?catalog=Destilados HTTP/1.1
###
POST {{host}}/Post HTTP/1.1
Content-Type: application/json

{
    "id":1,
    "name":"Juan",
    "imageLink":"Juan.jpg",
    "price":239,
    "stock":50,
    "category":{
        "id":1,
        "name":"Vino Blanco",
        "catalog":{
            "id":1,
            "name":"Vinos"
        }
    }
}
###
PUT {{host}}/Put HTTP/1.1
Content-Type: application/json

{
  "id": 1,
  "name": "Blue ",
  "imageLink": "https://vinosamerica.com/wp-content/uploads/2020/10/1530.jpg",
  "price": 239,
  "stock": 50,
  "category": {
    "id": 1,
    "name": "Vino Blanco",
    "catalog": {
      "id": 1,
      "name": "Vinos"
    }
  }
}
###
DELETE {{host}}/Delete?id=2 HTTP/1.1