### Se necesita la extension de REST Client para usar las rutas de abajo en vs code
###@host = http://25.98.13.19:5555
@host = https://localhost:5001
GET {{host}}/api/Catalog/Test HTTP/1.1
###
POST {{host}}/api/Catalog/GetAll HTTP/1.1
Content-Type: application/json

{
    "usuario":"Santi@hotmail.com",
    "informacion":"Mamey?"
}
###
POST {{host}}/api/Catalog/GetId HTTP/1.1
Content-Type: application/json

{
    "usuario":"Santi@hotmail.com",
    "informacion":"2"
}